name: icepeak
version: '0.7.0'
synopsis: Icepeak is a fast JSON document store with push notification support
license: BSD3
homepage: https://github.com/channable/icepeak
bug-reports: https://github.com/channable/icepeak/issues
category: web
author: Channable
maintainer: rkrzr
description: Icepeak is a fast JSON document store with push notification support.
synopsis: A fast JSON document store with push notification support.
copyright: (c) 2020, Channable
ghc-options:
- -Wall

dependencies:
- aeson                             >= 1.4.6 && < 1.5
- async                             >= 2.2.2 && < 2.3
- base                              >= 4.12.0 && < 4.13
- bytestring                        >= 0.10.8 && < 0.11
- containers                        >= 0.6.0 && < 0.7
- directory                         >= 1.3.3 && < 1.4
- hashable                          >= 1.2.0 && < 1.4
- http-types                        >= 0.12.3 && < 0.13
- jwt                               >= 0.10.0 && < 0.11
- monad-logger                      >= 0.3.31 && < 0.4
- mtl                               >= 2.2.2 && < 2.3
- network                           >= 2.8.0 && < 3.2
- optparse-applicative              >= 0.14.0 && < 0.16
- prometheus-client                 >= 1.0.0 && < 1.1
- prometheus-metrics-ghc            >= 1.0.0 && < 1.1
- random                            >= 1.1 && < 1.2
- raven-haskell                     >= 0.1.2 && < 0.2
- scotty                            >= 0.11.5 && < 0.12
- securemem                         >= 0.1.10 && < 0.2
- sqlite-simple                     >= 0.4.16 && < 0.5
- stm                               >= 2.5.0 && < 2.6
- text                              >= 1.2.3 && < 1.3
- time                              >= 1.8.0 && < 1.9
- unix                              >= 2.7.2 && < 2.8
- unordered-containers              >= 0.2.10 && < 0.3
- uuid                              >= 1.3.13 && < 1.4
- wai                               >= 3.2.2 && < 3.3
- wai-extra                         >= 3.0.29 && < 3.1
- wai-middleware-prometheus         >= 1.0.0 && < 1.1
- wai-websockets                    >= 3.0.1 && < 3.1
- warp                              >= 3.3.0 && < 3.4
- websockets                        >= 0.12.7 && < 0.13

library:
  source-dirs: src
  ghc-options:
  - -Wno-orphans
  - -Wno-unused-top-binds
  - -O2
  - -fno-ignore-asserts
  - -funbox-strict-fields
  exposed-modules:
  - AccessControl
  - Config
  - Core
  - HTTPMethodInvalid
  - HttpServer
  - JwtAuth
  - JwtMiddleware
  - Logger
  - Metrics
  - MetricsServer
  - Persistence
  - SentryLogging
  - Server
  - Store
  - Subscription
  - WebsocketServer

executables:
  icepeak:
    main: Main.hs
    source-dirs: app/Icepeak
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - ! '"-with-rtsopts=-N -I0"'
    dependencies:
    - icepeak

  icepeak-token-gen:
    main: Main.hs
    source-dirs: app/IcepeakTokenGen
    dependencies:
    - icepeak

tests:
  spec:
    main: Spec.hs
    source-dirs: tests
    ghc-options:
    - -Wno-orphans
    dependencies:
    - hspec
    - hspec-core
    - hspec-expectations
    - hspec-wai
    - QuickCheck
    - quickcheck-instances
    - icepeak
